version: "3.9"

services:
  yip:
    container_name: yip
    build:
      target: production
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - "THREADS=4"
      - "PORT=8000"
      - "FLAGS=--verbose --forwarded"
