version: "3.9"

services:
  yip:
    container_name: yip
    build:
      target: production
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - "THREADS=4"
      - "PORT=80"
      - "FLAGS=--verbose --forwarded"
